version: '3.8'

services:
  postgresql:
    image: postgres:15-alpine
    container_name: joblens_postgres
    environment:
      POSTGRES_DB: joblens_db
      POSTGRES_USER: joblens_user
      POSTGRES_PASSWORD: joblens_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U joblens_user -d joblens_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: joblens_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: joblens_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      ADMINER_DEFAULT_SERVER: postgresql

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: joblens_network
